djcelery/models.py, djcelery/snapshot.py, djcelery/utils.py
Hi!
I work for one company and in our project we use Django 1.6 with: 
*USE_TZ = False*
*TIME_ZONE = 'US/Pacific'*
Celery has following settings:
*CELERY_ENABLE_UTC = False*
*CELERY_TIMEZONE = TIME_ZONE*
The problem was that djcelery admin interface showed UTC time instead of *US/Pacific* as we wanted. I've found out that djcelery didn't make use of *CELERY_ENABLE_UTC* parameter, so I've added the support for this.
I believe that some of open issues might be connected: #192, #324, #292
=> Made use of CELERY_ENABLE_UTC

README.rst
and it the ReadTheDocs page on Django doesn't include 70% of the things required to get django-celery running that we see here in django-celery github readme.
=> The django-celery docs link is broken

docs/introduction.rst
South is deprecated because Django has migrations native now
=> updated docs about migrating celery in Django

djcelery/models.py
Fixes #399 
Hello, django-celery constantly trying to create new migration each time.
```python
operations = [
migrations.AlterField(
model_name='taskmeta',
name='status',
field=models.CharField(
default='PENDING', 
choices=[
('SUCCESS', 'SUCCESS'), 
('RETRY', 'RETRY'), 
('STARTED', 'STARTED'), 
('REVOKED', 'REVOKED'), 
('RECEIVED', 'RECEIVED'), 
('PENDING', 'PENDING'), 
('FAILURE', 'FAILURE')
], 
max_length=50, 
verbose_name='state'
),
),
]
```
```python
operations = [
migrations.AlterField(
model_name='taskmeta',
name='status',
field=models.CharField(
choices=[
('RETRY', 'RETRY'), 
('RECEIVED', 'RECEIVED'), 
('PENDING', 'PENDING'), 
('FAILURE', 'FAILURE'), 
('SUCCESS', 'SUCCESS'), 
('REVOKED', 'REVOKED'), 
('STARTED', 'STARTED')
], 
verbose_name='state', 
max_length=50, …
```
=> prevent redundant migrations for py3 and #399

djcelery/schedulers.py
It appears that Django 1.10 removes the `_default_manager` attribute from model instances (per: https://code.djangoproject.com/ticket/26652).  django-celery currently uses this attribute in the `ModelEntry` class in schedulers.py (https://github.com/celery/django-celery/blob/bac46064cf19f6de026a3ed30b54569fb1aa325e/djcelery/schedulers.py#L98).  As a result, using django-celery with Django 1.10 results in errors like this:
```
[2016-06-25 20:14:42,098: ERROR/Beat] Process Beat
Traceback (most recent call last):
File "/Users/mfenniak/.virtualenvs/iohint-background/lib/python3.5/site-packages/billiard/process.py", line 292, in _bootstrap
self.run()
File "/Users/mfenniak/.virtualenvs/iohint-background/lib/python3.5/site-packages/celery/beat.py", line 553, in run …
```
=> Django 1.10 incompatibility: model instance has no _default_manager attribute

djcelery/migrations/0001_initial.py
This avoids a new migration being created on Python 3.
=> Converted bytestrings to strings in migration.

djcelery/templates/admin/djcelery/change_list.html
In admin interface, change this:
```Home › › Crontabs```
To this:
```Home › Djcelery › Crontabs```
Template code stolen from Django 1.7rc1.
=> Fix app label missing in admin interface

tox.ini
**Problem**
`flake8` is being run against the root directory. I think it does not make much sense as we should not be verifying dependencies that are installed under `.tox` directory, e.g.:
```
./.tox/flake8/lib/python2.7/os.py:35:0: E302 expected 2 blank lines, found 1
```
**Solution**
Only 'flake8' the `djcelery` package. This should improve the travis build time by up to 2 minutes.
=> Only run flake8 against djcelery package

djcelery/management/base.py
The old option_list is no longer supported by django 1.10, and instead a function should be provided to insert the custom options into the argparse Parser.
Fixes (hopefully) #447 
Prods to @lguibert for investigating this
=> Fix management command handling for django >= 1.10

Changelog, djcelery/migrations/0001_initial.py, djcelery/models.py
Fixed some warning you can see if you run the tests with `python -Wall tests/manage.py test`.
The [django documentation](https://docs.djangoproject.com/en/1.10/ref/models/fields/#foreignkey) tells that the field "on_delete" will be mandatory on foreign keys. The default value is `models.CASCADE`.
=> Fixed a bunch of django 2.0 deprecations.

Changelog, djcelery/loaders.py, djcelery/tests/test_schedulers.py, djcelery/tests/test_views.py, tests/settings.py, tox.ini
Also, added `-Wall` to tox config so that all warnings would be reported.
Resolved warnings:
```
RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
RemovedInDjango20Warning: Importing from django.core.urlresolvers is deprecated in favor of django.urls.
RemovedInDjango20Warning: Old-style middleware using settings.MIDDLEWARE_CLASSES is deprecated. Update your middleware and use settings.MIDDLEWARE instead.
DeprecationWarning: assertDictContainsSubset is deprecated
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/vytis/src/django-celery/tests/someapp/tasks.py' mode='U' encoding='utf-8'>
```
=> Resolved some warnings in tests.

djcelery/schedulers.py
Useful for debugging purposes; it's nice to know whether any tasks are actually being sync'ed.
=> Show number of syncing entries in the log

.gitignore, Changelog, djcelery/admin.py, djcelery/tests/test_admin.py
Add enable/disable actions in PeriodicTaskAdmin. Extend list_display
and search_fields. Write unit tests.
This also contains #427 and #357
=> PeriodicTaskAdmin enhancements

djcelery/admin.py, djcelery/tests/test_admin.py
When selecting the admin action "Enable/Disable selected periodic tasks", celery beat is not aware of the update and continues executing newly disabled periodic tasks and ignoring newly enabled periodic tasks.
Call PeriodicTasks.changed after the update is performed.
PeriodicTask.save is overriden in djcelery, so I'm unsure if djcelery should be calling the .save() method instead of doing a bulk update of the enabled flag.
=> Update PeriodicTasks on bulk task enable/disable in admin.

djcelery/admin.py, djcelery/loaders.py, djcelery/management/base.py, djcelery/models.py, djcelery/mon.py, djcelery/picklefield.py, djcelery/tests/test_admin.py, djcelery/tests/test_worker_job.py
When django-celery tries to find related module from installed apps, the loading fails when `tasks` is a module inside one of the installed apps.
`imp.find_module` returns first argument as `None` if app_path is
a module and not a file
these changes will call close method only if the file is retuned
more information:
https://docs.python.org/2/library/imp.html#imp.find_module
=> Fixes close method call when imp returns None in loaders

djcelery/backends/database.py
For bug #496
To go along with this: https://github.com/celery/django-celery/pull/516/commits/12b7646f455527d2bef51508c105137a02832cae
and this: https://github.com/celery/django-celery/pull/510
=> Another `celery.utils.time` fix

djcelery/schedulers.py, djcelery/tests/test_schedulers.py
`ModelEntry` was not checking if there is `interval` value in DB when updating scheduled task from settings dict.
The result was unexpected (and frustrating) behavior when one decides that he need more fine grained control over execution schedule and change only `schedule` from `timedelta` to `crontab`.
I propose to set schedule fields to `None` prior setting a proper value.
=> Fix DatabaseScheduler behavior when schedule is changed from interval to crontab

README.rst
$ rst2html.py --version; rst2html.py README.rst > /dev/null
rst2html.py (Docutils 0.12 [release], Python 3.4.3, on linux)
README.rst:73: (ERROR/3) Unknown target name: "django-celery documentation".
Based on my experience, this should also fix the formatting issue on the
pypi.python.org site
changed the link based on the intent of the original commit that removed it, 27bec1e20af79df83061105127c123715c3d1011
=> fixes rst 'unkown target' error

djcelery/admin.py
Improves periodic tasks admin, tasks are better clickable.
Old situation: only `enabled` is clickable. This is not clear because it uses an icon. 
New situation, `periodic task` and `task name` are also clickable. This improves navigation in the periodic task admin:
=> Improves periodic tasks admin, tasks are better clickable.

djcelery/tests/test_schedulers.py
Was getting the following error:
```
nosetests /builddir/build/BUILD/django-celery-3.2.1/tests/../djcelery/tests  --cover3-package=djcelery --cover3-branch --cover3-exclude=djcelery,djcelery.tests.*,djcelery.management.*,djcelery.contrib.* --verbosity=1
Creating test database for alias 'default'...
.............................................F..........................
======================================================================
FAIL: test_should_sync (djcelery.tests.test_schedulers.test_DatabaseScheduler)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/builddir/build/BUILD/django-celery-3.2.1/tests/../djcelery/tests/test_schedulers.py", line 159, in test_should_sync
self.assertTrue(self.s.should_sync()) …
```
=> Fixes should_sync() test so that it passes with celery v3.1.24

djcelery/admin.py, djcelery/admin_utils.py
Fixes #541 
Already test it under Django 1.11.10 and 2.0.1
=> Fix incorrect display of html form with Django 2.0

FAQ
Update FAQ to demonstrate `translation.override` instead of `translation.activate` for switching language inside a task. The override function is safer and simpler.
=> Improve translation notes in the FAQ

djcelery/db.py, djcelery/loaders.py, djcelery/management/base.py, djcelery/management/commands/celery.py, djcelery/management/commands/celerybeat.py, djcelery/management/commands/celerycam.py, djcelery/management/commands/celeryd.py, djcelery/management/commands/celerymon.py, djcelery/management/commands/djcelerymon.py, djcelery/schedulers.py, djcelery/utils.py
There's a bug when run `python manage celery` related to attribute `preload_options` not existed in `CeleryCommand`.
=> Fix bug when run command `celery`

README.rst, djcelery/management/commands/celery.py, djcelery/management/commands/celerybeat.py, djcelery/management/commands/celerycam.py, djcelery/management/commands/celeryd.py, djcelery/management/commands/celerymon.py, djcelery/management/commands/djcelerymon.py, docs/introduction.rst
In 3.3.0 [options were broken](5d1ecb09c6304d22cc447c7c08fba0bd1febc2ef) by messing up tuples and lists
=> Foolproof prevention via strict tuples. Fixes #573

djcelery/managers.py
`@@tx_isolation` is deprecated since MYSQL 5.7.20, we should use `@@transaction_isolation` instead
https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_tx_isolation
Fix suggested by [sqlalchemy](https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_3/lib/sqlalchemy/dialects/mysql/base.py#L2193) realization
=> issue #579. @@tx_isolation is deprecated since MYSQL 5.7.20

djcelery/management/commands/celery.py
You can see diff information.
<pre>
<--
diff --git a/djcelery/management/commands/celery.py b/djcelery/management/commands/celery.py
index 0ee878d..82cf303 100644
--- a/djcelery/management/commands/celery.py
+++ b/djcelery/management/commands/celery.py
@@ -13,7 +13,7 @@ class Command(CeleryCommand):
help = 'celery commands, see celery help'
options = (
tuple(CeleryCommand.options) +
-        tuple(base.get_options()) +
+        tuple(base.get_options() or ()) +
tuple(getattr(base, 'preload_options', ()))
)
-->
</pre>
=> Fix bug for adding a default value to celery.py when base.get_options return None

djcelery/schedulers.py
Fixes https://github.com/celery/django-celery/issues/590
=> Change DatabaseScheduler.max_interval to match Celery's default Scheduler behaviour

README.rst
The README.rst used to point to http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html , but that link directs to a 404. The new link is https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html
=> Replaced old Celery docs URL with new docs link

README.rst, docs/introduction.rst
I know this package is no longer recommended, so I'm not sure if anyone cares, but I was looking through the readme and discovered that the wiki link is broken. Making an educated guess about where it's supposed to go.
=> Fix broken wiki links
